import express, { Request, Response, Router } from 'express';
import { z } from 'zod';
import bcrypt from 'bcrypt';
import jwt from 'jsonwebtoken';
import { getUsersCollection } from '../db/astra-client';
import { config } from '../config'; // For JWT secret

export const authRouter: Router = express.Router();

// --- Validation Schemas ---
const registerSchema = z.object({
    name: z.string().min(1, 'Name is required'),
    email: z.string().email('Invalid email address'),
    password: z.string().min(8, 'Password must be at least 8 characters long'),
});

const loginSchema = z.object({
    email: z.string().email(),
    password: z.string(),
});

// --- Middleware for Async Handlers (Optional but good practice) ---
const asyncHandler = (fn: (req: Request, res: Response, next: express.NextFunction) => Promise<any>) => 
    (req: Request, res: Response, next: express.NextFunction) => {
        Promise.resolve(fn(req, res, next)).catch(next);
};

// --- Routes ---

// [POST] /api/auth/register - Register a new user
authRouter.post('/register', asyncHandler(async (req: Request, res: Response) => {
    const validated = registerSchema.parse(req.body); // Throws ZodError on failure
    const usersCollection = getUsersCollection();

    // Check if user already exists
    const existingUser = await usersCollection.findOne({ email: validated.email });
    if (existingUser) {
        return res.status(409).json({ message: 'Email already in use' }); // 409 Conflict
    }

    // Hash password
    const saltRounds = 10; // Standard salt rounds
    const passwordHash = await bcrypt.hash(validated.password, saltRounds);

    // Create user document (ensure structure matches UserDocument in astra-client.ts)
    const newUserDocument = {
        name: validated.name,
        email: validated.email,
        password: passwordHash, // Store the hash, not the plain password
        // _id will be generated by Astra DB if not provided
        // Add other default fields if needed, e.g., createdAt
    };

    const result = await usersCollection.insertOne(newUserDocument);

    if (!result.insertedId) {
        throw new Error('Failed to register user.'); // Should trigger global error handler
    }

    // Respond with success (don't send back password hash)
    res.status(201).json({ 
        message: 'User registered successfully', 
        userId: result.insertedId 
    });
}));

// [POST] /api/auth/login - Login a user
authRouter.post('/login', asyncHandler(async (req: Request, res: Response) => {
    const validated = loginSchema.parse(req.body);
    const usersCollection = getUsersCollection();

    // Find user by email
    const user = await usersCollection.findOne({ email: validated.email });
    if (!user) {
        return res.status(401).json({ message: 'Invalid email or password' }); // Unauthorized
    }

    // Compare submitted password with stored hash
    const isPasswordValid = await bcrypt.compare(validated.password, user.password);
    if (!isPasswordValid) {
        return res.status(401).json({ message: 'Invalid email or password' }); // Unauthorized
    }

    // Generate JWT token
    const tokenPayload = { userId: user._id, email: user.email }; // Include necessary info
    const token = jwt.sign(
        tokenPayload, 
        config.jwtSecret, 
        { expiresIn: config.jwtExpiresIn || '1h' } // Use expiration from config or default
    );

    // Respond with token (don't send user password hash)
    res.status(200).json({ 
        message: 'Login successful', 
        token: token, 
        user: { id: user._id, email: user.email, name: (user as any).name } // Use name here, casting `user` is still needed due to UserDocument mismatch
    }); 
})); 